# appletviewer
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/appletviewer.1
# using Type1
complete -c appletviewer -o debug --description 'Starts the applet viewer in the Java debugger, … [See Man Page]'
complete -c appletviewer -o encoding --description 'Specify the input HTML file encoding name.'

