# extcheck
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/extcheck.1
# using Type1
complete -c extcheck -o verbose --description 'Lists Jar files in the extension directory as they are checked.'

