# jar
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/jar.1
# using Type1
complete -c jar -o Cdir --description 'Temporarily changes directories (\\f2cd\\f2dir) d… [See Man Page]'

