# jcmd
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/jcmd.1
# using Type1
complete -c jcmd -s l --description 'Prints the list of running Java processes with … [See Man Page]'
complete -c jcmd -s h --description 'Prints a help message.'

