# jconsole
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/jconsole.1
# using Type1
complete -c jconsole -o interval --description 'Set the update interval to \\f2n seconds (default is 4 seconds).'
complete -c jconsole -o notile --description 'Do not tile windows initially (for two or more connections).'
complete -c jconsole -o pluginpath --description 'Specify a list of directories or JAR files whic… [See Man Page]'
complete -c jconsole -o version --description 'Output version information and exit.'
complete -c jconsole -o help --description 'Output help message and exit.'

