# jinfo
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/jinfo.1
# using Type1
complete -c jinfo -o flag --description 'prints the name and value of the given command line flag. br.'
complete -c jinfo -o ']name' --description 'enables or disables the given boolean command line flag. br.'
complete -c jinfo -o flags --description 'prints command line flags passed to the JVM.  pairs. br.'
complete -c jinfo -o sysprops --description 'prints Java System properties as name, value pairs. br.'
complete -c jinfo -s h --description 'prints a help message.'

