# jstat
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/jstat.1
# using Type1
complete -c jstat -o help --description 'Display help message.'
complete -c jstat -o options --description 'Display list of statistics options.'
complete -c jstat -o statOption --description 'Determines the statistics information that \\f3jstat displays.'
complete -c jstat -s h --description 'Display a column header every \\f2n samples (out… [See Man Page]'
complete -c jstat -s t --description 'Display a timestamp column as the first column of output.'

