# jstatd
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/jstatd.1
# using Type1
complete -c jstatd -o nr --description 'Do not attempt to create an internal RMI regist… [See Man Page]'
complete -c jstatd -s p --description 'Port number where the RMI registry is expected … [See Man Page]'
complete -c jstatd -s n --description 'Name to which the remote RMI object is bound in… [See Man Page]'

