# jstack
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/jstack.1
# using Type1
complete -c jstack -s F --description 'Force a stack dump when \'jstack [-l] pid\' does not respond.'
complete -c jstack -s l --description 'Long listing.'
complete -c jstack -s m --description 'prints mixed mode (both Java and native C/C++ f… [See Man Page]'
complete -c jstack -s h --description 'prints a help message. br . br.'

