# jvisualvm
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/jvisualvm.1
# using Deroffing man parser
complete -c jvisualvm -o 'J<jvm_option>' --description 'Pass this <jvm_option> to the JVM software.'

