# native2ascii
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/native2ascii.1
# using Type1
complete -c native2ascii -o reverse --description 'Perform the reverse operation: Convert a file e… [See Man Page]'
complete -c native2ascii -o encoding --description 'Specifies the name of the character encoding to… [See Man Page]'

