# rmiregistry
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/rmiregistry.1
# using Deroffing man parser
complete -c rmiregistry -s J --description 'Used in conjunction with any java option, it pa… [See Man Page]'

