# serialver
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/serialver.1
# using Type1
complete -c serialver -o classpath --description 'Set search path for application classes and resources. RE  .'
complete -c serialver -o show --description 'Displays a simple user interface.'

