# servertool
# Autogenerated from man page /mnt/lv01/nishikawasasaki/.gentoo/java-config-2/current-user-vm/man/man1/servertool.1
# using Type1
complete -c servertool -o ORBInitialHost --description 'Specifies the host machine on which the name se… [See Man Page]'

